server:
    port: 8080

spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/123123
            authentication-database: admin
            username: dbAdmin
            password: 123123
